# Use the bitnami/java:1.8.151-r0 as the base image
FROM opensuse/leap

# Install python3.11
RUN zypper refresh && zypper update -y && zypper install -y python311

# Copy the "Tools" directory into the container at /opt/
COPY Tools /opt/
COPY jre-8u381-linux-x64.rpm /opt/

# Set the working directory in the container
WORKDIR /opt
# Install jre
RUN rpm -ivh jre-8u381-linux-x64.rpm


CMD ["java", "-jar", "DIGen.jar", "-sf", "3", "-o", "D1"]
