global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'host-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
            instance: 'prometheus-server'

  - job_name: node_exporter
    static_configs:
    - targets: ['10.16.45.131:9100']
      labels:
        instance: 'SOURCE'

    - targets: ['10.16.45.130:9100']
      labels:
        instance: 'TARGET'

    - targets: ['10.16.45.133:9100']
      labels:
        instance: 'ETL'

  - job_name: psql_exporter
    static_configs:
    - targets: ['10.16.45.131:9187']
      labels:
        instance: 'SOURCE'

    - targets: ['10.16.45.130:9187']
      labels:
        instance: 'TARGET'

remote_write:
  - url: "http://localhost:8086/api/v1/prom/write?db=prometheus&u=ivan&p=Ran22890"